ports:
  - port: 5000
    onOpen: open-preview

tasks:
#  - before: |
#      export FLASK_APP=flaskr
#      export FLASK_ENV=development
  - name: Setup & Prepare
    init: |
      pip install -e .
      pip install -r backend/requirements.txt
      docker-compose up -d
      gp sync-done setup
  - name: Run webserver
    init: gp sync-await setup
    command: |
      cd backend
      uvicorn main:app --reload
vscode:
  extensions:
    - ms-python.python
    - eamodio.gitlens